prgrms-web-devcourse/Team_Coco_FE

- src/components/ActionsMenu/ActionsMenu.tsx
- src/components/ActionsMenu/index.ts
- src/components/User/User.tsx
- src/components/User/index.ts
- src/features/posts/components/Post/Post.tsx
- src/pages/profile/ProfilePage.tsx
- src/utils/children.ts
- 사전에 논의한 대로 액션들에 대한 메뉴와 유저 정보를 보여주는 컴포넌트를 공통 컴포넌트로 추출하였습니다.
- 유효한 child만 검증할 수 있는 util 함수를 정의하였습니다.
- 유저 정보 컴포넌트의 경우 디자인 상 크게 두 가지 크기로만 사용되여 작은 크기 -> sm, 큰 크기 -> md라는 사이즈로 지정하였습니다.
기본 화면             | 액션 메뉴 클릭 시
:-------------------------:|:-------------------------:
> feat: 마이페이지 markup

- src/components/DatePicker/DatePicker.tsx
- src/features/posts/components/PostsSearchForm/PostsSearchForm.tsx
- React-hook-form과의 연동을 위해 최소한의 커스터마이징만 수행하였습니다.
- 전반적인 스타일링은 나중으로 미뤄두어야 할 것 같습니다.
> refactor: DatePicker 컴포넌트 리팩터링

- package.json
- proxy 경로를 설정하여 모든 api 요청에 대해 백엔드 도메인에서 요청이 수행된 것처럼 여기게끔 합니다.
```typescript
useEffect(() => {
fetch("/schedules")
.then((res) => {
return res.json();
})
.then((json) => {
console.log({ json });
});
}, []);
```
- 위와 같은 형태는 단순한 예시로써 데이터 fetching이 가능합니다.
> feat: proxy 경로 설정

- src/features/memo/components/MemoContent/MemoContent.tsx
- src/features/memo/components/MemoHeader/MemoHeader.tsx
- src/features/schedules/components/Schedule/Schedule.tsx
- src/features/vote/components/BodyBeforeVote/BodyBeforeVote.tsx
- src/features/vote/components/VoteHeader/VoteHeader.tsx
- src/pages/note/NotePage.tsx
- src/pages/schedules/SchedulePage.tsx
- 일정 디테일 페이지로 이동
- 메모 및 투표 페이지로 이동
> feat: schedule 하위 페이지들 라우팅 연결

- netifly.toml
- src/config/index.ts
> feat: 2차 배포 설정 추가

- src/components/GoToUpdateButton/GoToUpdateButton.tsx
- src/lib/axios.ts
- src/pages/note/NotePage.tsx
- src/pages/posts/PostUpdatePage.tsx
- src/pages/posts/PostsPage.tsx
- src/pages/schedules/ScheduleUpdatePage.tsx
- src/pages/schedules/SchedulesPage.tsx
- GoTo 버튼을 배치하고 GoToUpdate 버튼을 Portal을 사용하는 형태로 리팩터링 하였습니다.
> refactor: GoTo 버튼 리팩터링 및 반영

- src/components/User/User.tsx
- src/features/auth/components/RegisterForm/RegisterForm.tsx
- src/features/auth/hooks/useAuthData.ts
- src/features/posts/components/LikedPosts/LikedPosts.tsx
- src/features/posts/components/LikedPosts/index.ts
- src/features/posts/components/MyPosts/MyPosts.tsx
- src/features/posts/components/MyPosts/index.ts
- src/features/posts/components/Post/Post.tsx
- src/features/posts/components/PostUpdateForm/PostUpdateForm.tsx
- src/features/posts/components/Posts/Posts.tsx
- src/features/posts/components/PostsSearchForm/PostsSearchForm.tsx
- src/features/posts/components/SortBySelect/SortBySelect.tsx
- src/features/posts/components/index.ts
- src/features/posts/hooks/index.ts
- src/features/posts/hooks/usePostsData.ts
- src/features/posts/types/index.ts
- src/features/user/hooks/index.ts
- src/features/user/hooks/useUsersData.ts
- src/features/user/types/index.ts
- src/lib/react-query.ts
- src/pages/posts/PostsPage.tsx
- src/pages/profile/ProfilePage.tsx
- src/utils/object.ts
- src/utils/types.ts
- posts, profile 페이지에 대한 query 코드만 붙여둔 상태입니다.
- 일정 생성이 가능해졌으니 바로 posts CRUD 작업 수행하겠습니다~!
> feat: profile 및 posts 수정 코드 반영

- src/features/auth/components/RegisterForm/RegisterForm.tsx
- src/features/auth/types/index.ts
- src/features/posts/components/AddCommentForm/AddCommentForm.tsx
- src/features/posts/components/AddCommentForm/index.ts
- src/features/posts/components/Comment/Comment.tsx
- src/features/posts/components/Comments/Comments.tsx
- src/features/posts/components/Comments/index.ts
- src/features/posts/components/Post/Post.tsx
- src/features/posts/components/PostDetailContent/PostDetailContent.tsx
- src/features/posts/components/PostDetailHeader/PostDetailHeader.tsx
- src/features/posts/components/PostLikeButton/PostLikeButton.tsx
- src/features/posts/components/PostLikeButton/index.ts
- src/features/posts/components/PostUpdateForm/PostUpdateForm.tsx
- src/features/posts/components/Posts/Posts.tsx
- src/features/posts/components/PostsSearchForm/PostsSearchForm.tsx
- src/features/posts/components/SortBySelect/SortBySelect.tsx
- src/features/posts/components/index.ts
- src/features/posts/constants/index.ts
- src/features/posts/hooks/index.ts
- src/features/posts/hooks/useCommentsData.ts
- src/features/posts/hooks/usePostsData.ts
- src/features/posts/types/index.ts
- src/features/user/types/index.ts
- src/pages/posts/PostPage.tsx
- src/pages/posts/PostUpdatePage.tsx
- src/pages/posts/PostsPage.tsx
- src/utils/date.ts
- src/utils/object.ts
- src/utils/types.ts
- posts 생성, 조회
- 댓글 생성, 좋아요 토글 기능 추가했습니다.
- 시간 관계 상 빠르게 구현하느라 코드가 엉망이네요...
> feat: posts 생성, 조회, 댓글 추가 구현

- src/features/schedules/components/Checklist/Checklist.tsx
- src/features/schedules/components/CustomCheckBox/CustomCheckBox.tsx
- src/features/schedules/components/CustomCheckBox/index.ts
- CustomCheckBox에서 stylelint 에러 수정하였습니다.
- CustomCheckBox import 시 파일명을 정정하였습니다.
> fix: stylelint 순서 에러 처리 및 import 파일명 수정

- src/features/memo/components/MemoContent/MemoContent.tsx
- src/features/memo/components/MemoUpdateForm/MemoUpdateForm.tsx
- src/features/memo/hooks/useMemoData.ts
- src/features/note/components/MemoList/MemoList.tsx
- src/features/note/components/VoteList/VoteList.tsx
- src/features/vote/components/BodyAfterVote/BodyAfterVote.tsx
- src/features/vote/components/BodyBeforeVote/BodyBeforeVote.tsx
- src/features/vote/components/VoteUpdateForm/VoteUpdateForm.tsx
- src/features/vote/hooks/useVoteData.ts
- src/pages/memo/MemoPage.tsx
- src/pages/memo/MemoUpdatePage.tsx
- src/pages/note/NotePage.tsx
- src/pages/vote/VotePage.tsx
- 메모 수정 기능 추가
- 투표  생성 기능 추가
- 스타일 및 뒤로가기 오류 수정
**투표 행사**
현재 api 가 고장난 상태라서 추후 백엔드 작업이 끝나면 바로 연결될 것 같습니다.
> feat: 투표 생성 react-query, note-page 스타일 수정

- src/features/auth/components/RegisterForm/RegisterForm.tsx
- src/features/auth/types/index.ts
- 회원가입 시 전달하는 성별의 타입이 서버측과 맞지 않아 hotfix를 수행합니다!
> hotfix: 회원가입 시 성별 타입 수정

- src/features/schedules/components/Checklist/Checklist.tsx
- src/features/schedules/components/CustomCheckBox/CustomCheckBox.tsx
- src/features/schedules/hooks/useChecklistData.ts
- 일정(Schedule) 내 체크리스트 부분에 낙관적 업데이트가 적용되며, 발생하는 오류들을 수정하였습니다.
- 원인 : checklistId가 미처 서버에서 받아지지 않아 undefined인 상태인데, 체크(PATCH), 삭제(DELETE) 요청 시 발생하는 이슈였습니다. 
- 해결 
1. 아래 사진처럼 낙관적 업데이트로 id 없이 렌더링되는 리스트일 시, 체크(PATCH), 삭제(DELETE) 기능이 있는 UI(checkbox, button)들을 해당 시점에만 disabled하도록 하였습니다.
2. 근본적인 Error를 처리하기 위해, react-query내에 onError 코드를 추가하였습니다.
> fix: 일정(schedule) 낙관적 업데이트 관련 에러

- src/components/GoToBackButton/GoToBackButton.tsx
화면 스타일 이슈로 target 유무 모두 navigate로 동작하도록 수정
> fix: goToBack 버튼컴포넌트 navigate로  변경

- src/features/schedules/components/ChecklistForm/ChecklistForm.tsx
- src/features/schedules/components/ScheduleDetail/ScheduleDetail.tsx
일정 (Schedule) ChecklistForm에 yup을 이용한 validation을 추가합니다.
- day : 0~7까지 , number
- title: 1 ~16까지, string
> fix: 일정 (Schedule) 체크리스트 validation 추가

- src/features/schedules/components/Schedule/Schedule.tsx
- src/features/schedules/components/ScheduleDetail/ScheduleDetail.tsx
- src/features/schedules/components/Schedules/Schedules.tsx
- src/features/schedules/hooks/useScheduleData.ts
react-query를 이용한
- Schedule가 최근 생성 순으로 정렬됩니다.
- Schedule 삭제 api를 연동하였습니다.
- Schedule 생성 및 삭제 시 낙관적 업데이트가 적용되었습니다.
- Schedule 금일 당일치기로 생성해도 여행 완료로 뜨는 이슈 해결
생성 시 낙관적 업데이트(spinner) | 삭제 시 AlertDialog
:-------------------------:|:-------------------------:
> feat: 일정(schedule) 삭제 react-query 연동 

- src/features/posts/components/Post/Post.tsx
- src/features/posts/components/PostDetailHeader/PostDetailHeader.tsx
- src/features/posts/components/PostUpdateForm/PostUpdateForm.tsx
- src/features/posts/components/PostsSearchForm/PostsSearchForm.tsx
- src/routes/index.tsx
- 라우팅 마다 스크롤이 유지될 필요가 없다 판단하여 ScrollToTop 컴포넌트를 추가하였습니다.
- 포스트 수정 시 초기값 주입을 위해 포스트 정보를 fetch 해오는 과정에서 input에 입력이 기본값으로 초기화되는 현상이 있어 이를 수정하였습니다.
- 도시 검색 조건 기본 값이 전체이므로 placeholder가 불필요하여 이를 제거하였습니다.
- 게시글 제목 사이즈를 조정하였습니다.
> feat: 게시글 관련 수정 사항 반영

- src/features/posts/components/PostDetailContent/PostDetailContent.tsx
- src/features/posts/components/PostUpdateForm/PostUpdateForm.tsx
- src/pages/posts/PostPage.tsx
- white-space: pre-line 속성을 정의하여 우선 개행이 렌더되도록 수정하였습니다.
- 추가적으로 게시글 조회 시 전체 일수 계산 로직을 반영하였습니다.
> hotfix: 게시글 본문 조회 및 수정 시 개행 반영

- src/features/posts/components/PostDetailContent/PostDetailContent.tsx
- src/features/posts/components/PostUpdateForm/PostUpdateForm.tsx
- src/pages/posts/PostPage.tsx
* fix: 게시글 본문 개행 삽입 및 일자 산정 로직 수정
* fix: 게시글 수정 시에도 개행 유지하도록 수정
> hotfix: 게시글 본문 조회 및 수정 시 개행 반영 (#86)

- src/features/memo/components/MemoContent/MemoContent.tsx
- src/features/memo/hooks/useMemoData.ts
- src/features/posts/components/PostDetailHeader/PostDetailHeader.tsx
- src/features/vote/components/BodyAfterVote/BodyAfterVote.tsx
- src/features/vote/components/BodyBeforeVote/BodyBeforeVote.tsx
- src/features/vote/components/VoteUpdateForm/VoteUpdateForm.tsx
- src/features/vote/hooks/useVoteData.ts
- src/pages/vote/VotePage.tsx
- 투표 관련 로직 수정 이후 렌더링 이슈가 생겨 변경하였습니다.
- 불필요한 import 모두 제거하였습니다.
> hotfix: 투표 관련 렌더링 및 로직 이슈 수정

- src/features/memo/components/MemoContent/MemoContent.tsx
- src/features/memo/hooks/useMemoData.ts
- src/features/posts/components/PostDetailHeader/PostDetailHeader.tsx
- src/features/vote/components/BodyAfterVote/BodyAfterVote.tsx
- src/features/vote/components/BodyBeforeVote/BodyBeforeVote.tsx
- src/features/vote/components/VoteUpdateForm/VoteUpdateForm.tsx
- src/features/vote/hooks/useVoteData.ts
- src/pages/vote/VotePage.tsx
* chore: 사용하지 않는 import 제거
* fix: 투표 관련 렌더링 및 로직 수정
> hotfix: 투표 관련 렌더링 및 로직 이슈 수정 (#88)

- netlify.toml
- package.json
> feat: API 서버 경로 변경

- README.md
- netlify.toml
- package.json
> 최종 배포 서버 URL 변경
